name: Build Electron App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run rbuild

      - name: Build Electron app
        run: npm run build

      - name: Upload Electron Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electron-build
          path: ebuild/
